### PR TITLE
feat(yield popper target as 'target')

### PR DESCRIPTION
**Pull request by kybishop**
I'm in the process of making ember-attacher tagless, and I'd have to duplicate a lot of ember-popper's behavior to calculate the target. Seems better to just take advantage of the work ember-popper has already done.

### CODE REVIEW

**Comment by pzuraq** [comment]
If I remember correctly, the way this was used before was you'd pass the target into a child component which would then set it on the attacher? Something feels off about that, may make sense to send an action instead with the parent element (`didFindParent` maybe?) but I'm not against this either, just feels a little funky.

**Comment by kybishop** [comment]
@pzuraq do you mean something like this?

```hbs
// ember-attacher.hbs
{{#ember-popper onFoundTarget=(action (mut target))}}
  {{yield}}
{{/ember-popper}}
```

**Comment by pzuraq** [comment]
Yeah, we're planning on doing something similar in vertical-collection. Sometimes it does make sense to send something up on initialization to register it, effectively

**Comment by kybishop** [comment]
Closing in favor of #32

**Pull request closed without merging**
