### PR TITLE
Remove map file from public assets

### PR DESCRIPTION
**Pull request by gojefferson**

### CODE REVIEW

**Comment by pzuraq** [comment]
The map files were added because of #46, production builds fail without them. Is there a reason to remove them in general?

**Comment by gojefferson** [comment]
I removed them because they were causing my deployments to fail. Removing that line locally enables me to deploy my app to our staging environment. Here's the issue I opened in ember-attacher. https://github.com/kybishop/ember-attacher/issues/87

Perhaps there's another way to resolve the issue that keeps everything working as desired?

**Comment by pzuraq** [comment]
Really weird. Yeah this points to something fundamentally wrong here if some production builds will fail with them and some will fail without them 🙃 

Can you post your ember-cli setup? Versions of cli and related addons and anything custom you might have with `ember-cli-uglify`, sourcemaps, and fingerprinting would definitely help

**Comment by gojefferson** [comment]
Sure, here are the relevant parts of ember-cli-build.js

```js
/* eslint-env node */
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

function getUrlPrefix(environment) {
  if (environment === 'production') {
    return 'https://assets.company.com/';
  }
  if (environment === 'staging') {
    return 'https://assets-staging.company.com/';
  }
  return '';
}

module.exports = function(defaults) {
  var environment = process.env.EMBER_ENV;

  var isProduction = ['production', 'staging'].indexOf(environment) > -1;

  var options = {
    minifyCSS: {
      enabled: isProduction
    },
    minifyJS: {
      enabled: isProduction
    },
    sourcemaps: {
      enabled: true
    },
    tests: process.env.EMBER_CLI_TEST_COMMAND || !isProduction,
    hinting: process.env.EMBER_CLI_TEST_COMMAND || !isProduction,
    fingerprint: {
      enabled: isProduction,
      prepend: getUrlPrefix(environment),
      extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'svg'],  // Default + svg
    }
  }

  let app = new EmberApp(defaults, options);

  return app.toTree();
};
```

And here are the relevant parts of config/deploy.js:

```js
    // do not gzip .map or .js files, sentry does not unzip
    ENV.gzip = {
      filePattern: '**/*.{css,json,ico,xml,txt,svg,eot,ttf,woff,woff2}',
    };

    // do not upload .map files to S3, sentry will map the correct .map files post-exception
    // see: https://docs.sentry.io/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry
    ENV.s3 = {
      filePattern: '**/*.{js,css,png,gif,ico,jpg,xml,txt,svg,swf,eot,ttf,woff,woff2,otf}',
    };

    ENV['s3-index'] = {
      allowOverwrite: true,
    };
```

I'm guessing my issue has something to do with the fact that we don't upload map files to s3 because of an issue with Sentry. Hrm...

**Comment by gojefferson** [comment]
And it looks like my deploy config was the source of the problem. Removing .map files from fingerprint.extensions resolves the issue. I'm closing the PR. Thanks!

**Pull request closed without merging**
