### PR TITLE
Pass correct popper element in the registerAPI #105

### LINKED ISSUE #105: api._popperElement is undefined
Hi, seems like there is a problem with the latest 0.10.0 release.

On my app, I always get that `api._popperElement` is undefined. I think this is because the API tries to get the `_popperElement` computed property before it returns.
1. the REF modifier sets the computed prop `_popperElement` in `ember-popper-base`.
2. Before that set returns, `_updatePopper`is called
3. at the end of `_updatePopper`, `registerAPI` is called with `_getPublicAPI`
4. Inside `_getPublicAPI` you are calling `_getPopperElement` which returns `_popperElement`.
5. Since the SET of `_popperElement` (point 1 abose) hasn't returned yet, it is still null.

Screenshot 2019-06-12 at 12 12 15

Tested on ember@3.10.1 or even @3.9.

### PR DESCRIPTION
**Pull request by urbany**
Fixes #105

### CODE REVIEW

**Comment by simonihmig** [comment]
Thanks @urbany for working on this! Indeed my latest changes seem to have introduced this. 😔

Apparently there is some missing test coverage. Would you be able to add a test case to https://github.com/kybishop/ember-popper/blob/master/tests/integration/components/ember-popper/register-api-test.js?

Also another test is failing here, but this might be the flakey one of #95. I already restarted Travis a number of times though...

**Comment by simonihmig** [comment]
>  I already restarted Travis a number of times though...

Ah yes, it has finally passed after the third retry 🤔. So seems not related...

**Comment by urbany** [comment]
@simonihmig test added (I confirmed the test fails without the fix) and passes with the fix. I noticed that some tests fail randomly, but all pass most times.

PS: Thank you for your work on this addon!

**Comment by simonihmig** [comment]
The failing test in Ember 2.18 is from the newly added test. It seems https://github.com/kybishop/ember-popper/pull/106/files#diff-255dc3991591e84507576a55a13a6173R52 returns `null` here!? 🤔

**Comment by urbany** [comment]
@simonihmig I tried to fix this but couldn't, don't know what's wrong sorry :s

**Comment by simonihmig** [comment]
@urbany I added a commit to your PR that should hopefully fix the failing test! It is related to [a bug](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/issues/64) in `ember-angle-bracket-invocation-polyfill`, which makes the attributes (here `class`) render after `didRender`.

Let's see what Travis thinks of this...

**Comment by simonihmig** [comment]
Published as 0.10.1! 🎉

**Comment by urbany** [comment]
@simonihmig great! Thank you for the help!

**Pull request merged**
