### PR TITLE
feat(flatten top-level options) placement, modifiers, eventsEnabled

### PR DESCRIPTION
**Pull request by kybishop**
As per #6, this is the beginning of flattening out some of Popper.js's options to make the addon more ergonomic.

`placement` and `flip` seem like obvious choices to make top-level, though I'm more on the fence about `arrow`. Leaving this PR up for a bit to attract any comments.

### CODE REVIEW

**Comment by kybishop** [comment]
@pzuraq am I right to think the legacy version you plan to use would have all commonly used options flattened into the main component due to lack of the `hash` helper?

If so, I'm happy to bake more flattened options into the top level.

**Comment by pzuraq** [comment]
So currently in our implementation we just have `placement`, `modifiers` and `eventEnabled`, which is working for us so far (very minimal usage though). I thought about bringing top level items like `flip` up, definitely not against it but it does open the Pandora's box of which ones we should make available.

**Comment by FezVrasta** [comment]
If you have better ideas for the Popper.js API please feel free to open an issue on my repo to discuss them for a future v2

**Comment by kybishop** [comment]
@FezVrasta no worries on Popper.js's API, it works great. I think it is good that options are contained to a single object instead of polluting the constructor with a ton of args/coupling.

Ember just lets us do some fancy things in templates that make it worthwhile to expose some of those options.

That said, I very much agree with @pzuraq that exposing the deeper-nested options opens a Pandora's box. Going to mess with Ember-attacher to see how the API looks with a simpler flattening of options, then likely revise this PR to match.

**Comment by kybishop** [comment]
API works great in Ember-attacher with a simple flattening of top-level options. Moving forward with this approach

**Comment by kybishop** [comment]
Renamed branch and merged in #11

**Pull request closed without merging**
